#
# \brief Default Travis for TCP Server Project
# \author Uilian Ries <uilianries@gmail.com>
#
dist: trusty

language: cpp

compiler: gcc

before_install:
  - sudo pip install conan

script:
  - ./install.sh
  - build/bin/test-tcp-server

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
