#
# \brief Default Travis for TCP Server Project
# \author Uilian Ries <uilianries@gmail.com>
#
dist: trusty

language: cpp

compiler: gcc

before_install:
  - sudo pip install conan

script:
  - mkdir build
  - cd build
  - conan install ..
  - cmake .. -DTRAVISCI=ON
  - cmake --build . --config release
  - make check
  - sudo make install

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
    - develop
